[
    {
        "id": 678,
        "name": "Never throw an exception from a Destructor",
        "href": "AIP/quality-rules/678",
        "critical": false,
        "weight": 5,
        "technologyNames": [
            "C++"
        ]
    },
    {
        "id": 4656,
        "name": "Avoid declaring throwing an exception and not throwing it",
        "href": "AIP/quality-rules/4656",
        "critical": false,
        "weight": 5,
        "technologyNames": [
            "JEE"
        ]
    },
    {
        "id": 7824,
        "name": "Avoid directly throwing instance of Exception class",
        "href": "AIP/quality-rules/7824",
        "critical": false,
        "weight": 5,
        "technologyNames": [
            "C#",
            "JEE",
            "VB.NET"
        ]
    },
    {
        "id": 1027090,
        "name": "Avoid improper instantiation of argument exceptions",
        "href": "AIP/quality-rules/1027090",
        "critical": false,
        "weight": 5,
        "technologyNames": [
            "C#",
            "VB.NET"
        ]
    },
    {
        "id": 1065026,
        "name": "Ensure exception objects are always caught by reference (C++)",
        "href": "AIP/quality-rules/1065026",
        "critical": false,
        "weight": 5,
        "technologyNames": [
            "C++"
        ]
    }
]
