[
    {
        "id": 678,
        "name": "Never throw an exception from a Destructor",
        "href": "AIP/quality-rules/678",
        "critical": true,
        "severity": 20,
        "technologyNames": [
            "C++"
        ]
    },
    {
        "id": 7824,
        "name": "Avoid directly throwing instance of Exception class",
        "href": "AIP/quality-rules/7824",
        "critical": true,
        "severity": 20,
        "technologyNames": [
            "C#",
            "JEE",
            "VB.NET"
        ]
    },
    {
        "id": 8412,
        "name": "\"CX_ROOT\" should not be used in TRY .. CATCH.. ENDTRY block",
        "href": "AIP/quality-rules/8412",
        "critical": true,
        "severity": 20,
        "technologyNames": [
            "ABAP"
        ]
    },
    {
        "id": 1020540,
        "name": "Avoid using $http success and error function",
        "href": "AIP/quality-rules/1020540",
        "critical": false,
        "severity": 10,
        "technologyNames": [
            "HTML5"
        ]
    },
    {
        "id": 1027090,
        "name": "Avoid improper instantiation of argument exceptions",
        "href": "AIP/quality-rules/1027090",
        "critical": false,
        "severity": 10,
        "technologyNames": [
            "C#",
            "VB.NET"
        ]
    }
]
