[
    {
        "id": 678,
        "name": "Never throw an exception from a Destructor",
        "href": "AIP/quality-rules/678",
        "critical": true,
        "severity": 20,
        "technologyNames": [
            "C++"
        ]
    },
    {
        "id": 4656,
        "name": "Ensure to throw an exception which has been declared",
        "href": "AIP/quality-rules/4656",
        "critical": false,
        "severity": 10,
        "technologyNames": [
            "JEE"
        ]
    },
    {
        "id": 7824,
        "name": "Always Subclass Exception and throw the subclassed Classes, do not throw the exception Exception.",
        "href": "AIP/quality-rules/7824",
        "critical": true,
        "severity": 20,
        "technologyNames": [
            "C#",
            "JEE",
            "VB.NET"
        ]
    },
    {
        "id": 1020450,
        "name": "Ensure you have overwritten component methods to properly catch errors",
        "href": "AIP/quality-rules/1020450",
        "critical": false,
        "severity": 10,
        "technologyNames": [
            "HTML5"
        ]
    },
    {
        "id": 1020856,
        "name": "Ensure you have overwritten component methods to properly catch errors",
        "href": "AIP/quality-rules/1020856",
        "critical": false,
        "severity": 10,
        "technologyNames": [
            "HTML5"
        ]
    },
    {
        "id": 1027090,
        "name": "Avoid improper instantiation of argument exceptions",
        "href": "AIP/quality-rules/1027090",
        "critical": false,
        "severity": 10,
        "technologyNames": [
            "C#",
            "VB.NET"
        ]
    }
]
